### ISSUE TITLE
Installation error on ubuntu 20.04

### ISSUE THREAD

**Issue by luigikitten** [spotify/basic-pitch#15]
Hi,
    I am trying to install on ubuntu 20.04 via virtualenv but I get some dependencies errors (details below).
Any idea? Thanks!
Luigi

--------
```
lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal


python3 --version
Python 3.8.10

python3 -m venv myvenv

. myvenv/bin/activate

python3 -m pip install basic-pitch --upgrade
Collecting basic-pitch
  Using cached basic-pitch-0.0.1.tar.gz (2.0 MB)
Collecting librosa>=0.8.0
  Using cached librosa-0.9.1-py3-none-any.whl (213 kB)
Collecting mir_eval>=0.6
  Using cached mir_eval-0.7.tar.gz (90 kB)
Collecting numpy<1.20,>=1.19.2
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
Collecting pretty_midi>=0.2.9
  Using cached pretty_midi-0.2.9.tar.gz (5.6 MB)
Collecting resampy>=0.2.2
  Using cached resampy-0.2.2.tar.gz (323 kB)
Collecting scipy>=1.4.1
  Using cached scipy-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)
Collecting tensorflow<2.7.0,>=2.4.1
  Using cached tensorflow-2.6.5-cp38-cp38-manylinux2010_x86_64.whl (464.3 MB)
Collecting typing_extensions
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting scikit-learn>=0.19.1
  Using cached scikit_learn-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31.2 MB)
Collecting pooch>=1.0
  Using cached pooch-1.6.0-py3-none-any.whl (56 kB)
Collecting audioread>=2.1.5
  Using cached audioread-2.1.9.tar.gz (377 kB)
Collecting decorator>=4.0.10
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting joblib>=0.14
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting soundfile>=0.10.2
  Using cached SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting numba>=0.45.1
  Using cached numba-0.55.2-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.4 MB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting mido>=1.1.16
  Using cached mido-1.2.10-py2.py3-none-any.whl (51 kB)
Collecting absl-py~=0.10
  Using cached absl_py-0.15.0-py3-none-any.whl (132 kB)
Collecting flatbuffers~=1.12.0
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting keras<2.7,>=2.6.0
  Using cached keras-2.6.0-py2.py3-none-any.whl (1.3 MB)
Collecting wheel~=0.35
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting wrapt~=1.12.1
  Using cached wrapt-1.12.1.tar.gz (27 kB)
Collecting clang~=5.0
  Using cached clang-5.0.tar.gz (30 kB)
Collecting tensorflow-estimator<2.7,>=2.6.0
  Using cached tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
Collecting h5py~=3.1.0
  Using cached h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
Collecting astunparse~=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting termcolor~=1.1.0
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Collecting grpcio<2.0,>=1.37.0
  Using cached grpcio-1.46.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
Collecting opt-einsum~=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting protobuf<3.20,>=3.9.2
  Using cached protobuf-3.19.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting google-pasta~=0.2
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting keras-preprocessing~=1.1.2
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting gast==0.4.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting tensorboard<2.7,>=2.6.0
  Using cached tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting appdirs>=1.3.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting requests>=2.19.0
  Using cached requests-2.28.0-py3-none-any.whl (62 kB)
Collecting cffi>=1.0
  Using cached cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Requirement already satisfied, skipping upgrade: setuptools in ./myvenv/lib/python3.8/site-packages (from numba>=0.45.1->librosa>=0.8.0->basic-pitch) (44.0.0)
Collecting llvmlite<0.39,>=0.38.0rc1
  Using cached llvmlite-0.38.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.7-py3-none-any.whl (97 kB)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-2.1.2-py3-none-any.whl (224 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.5.18.1-py3-none-any.whl (155 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting importlib-metadata>=4.4; python_version < "3.10"
  Using cached importlib_metadata-4.11.4-py3-none-any.whl (18 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.6"
  Using cached rsa-4.8-py3-none-any.whl (39 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting zipp>=0.5
  Using cached zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.0-py3-none-any.whl (151 kB)
Building wheels for collected packages: basic-pitch, mir-eval, pretty-midi, resampy, audioread, future, wrapt, clang, termcolor
  Building wheel for basic-pitch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/basic-pitch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/basic-pitch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-62e6q952
       cwd: /tmp/pip-install-02w9gg2x/basic-pitch/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for basic-pitch
  Running setup.py clean for basic-pitch
  Building wheel for mir-eval (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/mir-eval/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/mir-eval/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-l_jcqoln
       cwd: /tmp/pip-install-02w9gg2x/mir-eval/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for mir-eval
  Running setup.py clean for mir-eval
  Building wheel for pretty-midi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/pretty-midi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/pretty-midi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-utsolp75
       cwd: /tmp/pip-install-02w9gg2x/pretty-midi/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pretty-midi
  Running setup.py clean for pretty-midi
  Building wheel for resampy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/resampy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/resampy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-q0hvu8zc
       cwd: /tmp/pip-install-02w9gg2x/resampy/
  Complete output (8 lines):
  /tmp/pip-install-02w9gg2x/resampy/setup.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for resampy
  Running setup.py clean for resampy
  Building wheel for audioread (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/audioread/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/audioread/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-i0ctyww7
       cwd: /tmp/pip-install-02w9gg2x/audioread/
  Complete output (8 lines):
  /tmp/pip-install-02w9gg2x/audioread/setup.py:17: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for audioread
  Running setup.py clean for audioread
  Building wheel for future (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-w1ayku7x
       cwd: /tmp/pip-install-02w9gg2x/future/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for future
  Running setup.py clean for future
  Building wheel for wrapt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/wrapt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/wrapt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2f0z5drz
       cwd: /tmp/pip-install-02w9gg2x/wrapt/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for wrapt
  Running setup.py clean for wrapt
  Building wheel for clang (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/clang/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/clang/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_ulttlk9
       cwd: /tmp/pip-install-02w9gg2x/clang/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for clang
  Running setup.py clean for clang
  Building wheel for termcolor (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: ....../myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02w9gg2x/termcolor/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02w9gg2x/termcolor/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-42erj0wy
       cwd: /tmp/pip-install-02w9gg2x/termcolor/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for termcolor
  Running setup.py clean for termcolor
Failed to build basic-pitch mir-eval pretty-midi resampy audioread future wrapt clang termcolor
ERROR: tensorflow 2.6.5 has requirement six~=1.15.0, but you'll have six 1.16.0 which is incompatible.
ERROR: tensorflow 2.6.5 has requirement typing-extensions<3.11,>=3.7, but you'll have typing-extensions 4.2.0 which is incompatible.
Installing collected packages: numpy, threadpoolctl, scipy, joblib, scikit-learn, appdirs, pyparsing, packaging, urllib3, certifi, charset-normalizer, idna, requests, pooch, audioread, llvmlite, numba, six, resampy, decorator, pycparser, cffi, soundfile, librosa, future, mir-eval, mido, pretty-midi, absl-py, flatbuffers, keras, typing-extensions, wheel, wrapt, clang, tensorflow-estimator, h5py, astunparse, termcolor, grpcio, opt-einsum, protobuf, google-pasta, keras-preprocessing, gast, zipp, importlib-metadata, markdown, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, tensorboard-plugin-wit, tensorboard-data-server, oauthlib, requests-oauthlib, google-auth-oauthlib, werkzeug, tensorboard, tensorflow, basic-pitch
    Running setup.py install for audioread ... done
    Running setup.py install for resampy ... done
    Running setup.py install for future ... done
    Running setup.py install for mir-eval ... done
    Running setup.py install for pretty-midi ... done
    Running setup.py install for wrapt ... done
    Running setup.py install for clang ... done
    Running setup.py install for termcolor ... done
    Running setup.py install for basic-pitch ... done
Successfully installed absl-py-0.15.0 appdirs-1.4.4 astunparse-1.6.3 audioread-2.1.9 basic-pitch-0.0.1 cachetools-4.2.4 certifi-2022.5.18.1 cffi-1.15.0 charset-normalizer-2.0.12 clang-5.0 decorator-5.1.1 flatbuffers-1.12 future-0.18.2 gast-0.4.0 google-auth-1.35.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.46.3 h5py-3.1.0 idna-3.3 importlib-metadata-4.11.4 joblib-1.1.0 keras-2.6.0 keras-preprocessing-1.1.2 librosa-0.9.1 llvmlite-0.38.1 markdown-3.3.7 mido-1.2.10 mir-eval-0.7 numba-0.55.2 numpy-1.19.5 oauthlib-3.2.0 opt-einsum-3.3.0 packaging-21.3 pooch-1.6.0 pretty-midi-0.2.9 protobuf-3.19.4 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pyparsing-3.0.9 requests-2.28.0 requests-oauthlib-1.3.1 resampy-0.2.2 rsa-4.8 scikit-learn-1.1.1 scipy-1.8.1 six-1.16.0 soundfile-0.10.3.post1 tensorboard-2.6.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.6.5 tensorflow-estimator-2.6.0 termcolor-1.1.0 threadpoolctl-3.1.0 typing-extensions-4.2.0 urllib3-1.26.9 werkzeug-2.1.2 wheel-0.37.1 wrapt-1.12.1 zipp-3.8.0

 basic-pitch 
Traceback (most recent call last):
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.16.0 (....../myvenv/lib/python3.8/site-packages), Requirement.parse('six~=1.15.0'), {'tensorflow'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "....../myvenv/bin/basic-pitch", line 6, in <module>
    from pkg_resources import load_entry_point
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "....../myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'six~=1.15.0' distribution was not found and is required by tensorflow

```

**Comment by luigikitten** [comment]
Thanks it works now

You can close

Il Lun 13 Giu 2022, 17:51 David Rubinstein ***@***.***> ha
scritto:
