### ISSUE TITLE
AttributeError: module 'tensorflow.python.training.experimental.mixed_precision' has no attribute '_register_wrapper_optimizer_cls'

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [spotify/basic-pitch#32]
C:\Users\MohammedMehdiTBER>basic-pitch "C:\Users\MohammedMehdiTBER\Documents" "C:\Users\MohammedMehdiTBER\Downloads\mytrack.flac" --save-midi --multiple-pitch-bends
    
    ✨✨✨✨✨✨✨✨✨
    ✨ Basic Pitch  ✨
    ✨✨✨✨✨✨✨✨✨
    Traceback (most recent call last):
      File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "C:\Program Files\Python39\Scripts\basic-pitch.exe\__main__.py", line 7, in <module>
      File "C:\Program Files\Python39\lib\site-packages\basic_pitch\predict.py", line 107, in main
        from basic_pitch.inference import predict_and_save, verify_output_dir, verify_input_path
      File "C:\Program Files\Python39\lib\site-packages\basic_pitch\inference.py", line 125, in <module>
        audio_path: Union[pathlib.Path, str], model: keras.Model, debug_file: Optional[pathlib.Path] = None
      File "C:\Program Files\Python39\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 62, in __getattr__
        module = self._load()
      File "C:\Program Files\Python39\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 45, in _load
        module = importlib.import_module(self.__name__)
      File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python39\site-packages\keras\__init__.py", line 25, in <module>
        from keras import models
      File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python39\site-packages\keras\models.py", line 20, in <module>
        from keras import metrics as metrics_module
      File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python39\site-packages\keras\metrics.py", line 27, in <module>
        from keras import activations
      File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python39\site-packages\keras\activations.py", line 20, in <module>
        from keras.layers import advanced_activations
      File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python39\site-packages\keras\layers\__init__.py", line 24, in <module>
        from keras.engine.input_layer import Input
      File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python39\site-packages\keras\engine\input_layer.py", line 21, in <module>
        from keras.engine import base_layer
      File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python39\site-packages\keras\engine\base_layer.py", line 41, in <module>
        from keras.mixed_precision import loss_scale_optimizer
      File "C:\Users\MohammedMehdiTBER\AppData\Roaming\Python\Python39\site-packages\keras\mixed_precision\loss_scale_optimizer.py", line 1180, in <module>
        mixed_precision._register_wrapper_optimizer_cls(optimizer_v2.OptimizerV2,
    AttributeError: module 'tensorflow.python.training.experimental.mixed_precision' has no attribute '_register_wrapper_optimizer_cls'

**Comment by drubinstein** [comment]
Hi. What version of keras are you using? Is it one different than specified in basic pitch's requirements? [StackOverflow](https://stackoverflow.com/questions/66178738/attributeerror-module-tensorflow-python-training-experimental-mixed-precision) suggests an incorrect version is at fault here

**Comment by rabitt** [comment]
Closing due to inactivity - please feel free to reopen this if you are still having an issue.
